### ISSUE TITLE
German translation of Pager is mixed up

### ISSUE THREAD

**Issue by sfadschm** [codeigniter4/translations#132]
In the German (de) file for Pager.php the values of `previous` and `last` are mixed up.

Current implementation:
    
    'first'                  => 'Erste',
    'previous'               => 'Letzte',
    'next'                   => 'Weiter',
    'last'                   => 'Zurück',

Corrected:
    
    'first'                  => 'Erste',
    'previous'               => 'Zurück',
    'next'                   => 'Weiter',
    'last'                   => 'Letzte',

**Comment by lonnieezell** [comment]
Please submit a PR.

**Comment by sba** [comment]
I created pull request 
[](https://github.com/codeigniter4/translations/pull/134)

**Comment by sfadschm** [comment]
> 
> 
> I submitted the pull request
> #134

Thanks, should I close mine or will it automatically be closed?

**Comment by sba** [comment]
I think you can close this issue - not sure if it closes automatically...

**Comment by sfadschm** [comment]
Closing, as pull request is not linked here, so likely no automatic closing.
