### ISSUE TITLE
[HELP WANTED]: Update language strings to latest develop

### ISSUE THREAD

**Issue by paulbalandan** [codeigniter4/translations#148]
With the merge of #144 , language strings for translation are kept up to date with `codeigniter4/codeigniter4` repo. Originally, this was with `codeigniter4/framework` so the strings were updated up to the recent release `v4.0.4`.

We are recruiting the help from the community as well as the maintainers of the locales to update the translation sets with the language strings from the main repo. You can read on the latest [Contributing guide][1] and how to run the specific locale tests in the [Test README][2].

[1]: https://github.com/codeigniter4/translations/blob/develop/CONTRIBUTING.md
[2]: https://github.com/codeigniter4/translations/blob/develop/tests/README.md

**Checklist of Completed Locales**
- [ ] ar | Arabic
- [x] cs | Czech
- [x] de | German
- [ ] es | Spanish
- [ ] fa | Farsi
- [ ] fr | French
- [x] id | Indonesian
- [x] it | Italian
- [x] ja | Japanese
- [x] ko | Korean
- [ ] lt | Lithuanian
- [ ] lv | Latvian
- [ ] ml | Malayalam
- [ ] nl | Dutch
- [ ] no | Norwegian
- [ ] pl | Polish
- [ ] pt | Portuguese
- [x] pt-BR | Brazilian
- [ ] ru | Russian
- [x] si | Sinhala
- [x] sk | Slovak
- [x] sv-SE | Swedish - Sweden
- [ ] tr | Turkish
- [ ] uk | Ukrainian
- [ ] vi | Vietnamese
- [ ] zh-CN | Simple Chinese
- [ ] zh-TW | Traditional Chinese

*Please link your PRs here so we can keep track of the progress.*

**Comment by totoprayogo1916** [comment]
Lang ID updated see PR #149

**Comment by sfadschm** [comment]
I could take a look at `de` if @sba is busy. #81 should be handled beforehand maybe.

**Comment by paulbalandan** [comment]
@sfadschm please do so. The next release is around the corner and we hope to get this done by then.

**Comment by sfadschm** [comment]
On it. I just tried using the new test suite, but I get:
`Class 'CodeIgniter\Language\AbstractTranslationTestCase' not found in D:\GitHub\translations\tests\Language\GermanTranslationTest.php:17`
codeigniter4 is installed in `D:\GitHub\translations\vendor\`
I don't really get why it can't find the abstract case that is in the same folder. Maybe a namespace issue?
Working on Windows 10.

**Comment by paulbalandan** [comment]
I made that class on Windows 10. Probably missed running `composer update` first? Or your composer.json isn't updated yet?

**Comment by sfadschm** [comment]
Thanks, never tried composer, but this was quite easy :D

**Comment by sba** [comment]
@sfadschm you updated/translated all DE-strings, right? Or does it need my help?

**Comment by sfadschm** [comment]
@sba yes, they are done. There was only a few left.

**Comment by sfadschm** [comment]
@sba I think I will look through the old messages this evening, too and see if I find any issues. If you have time, it would be nice if you could scan any changes in the PR tomorrow.

**Comment by sba** [comment]
@sfadschm ok, I will check all DE-files tomorrow

**Comment by paulbalandan** [comment]
To @all , we have a new file to translate: `Security.php`. Maybe this just needs some copy paste.

**Comment by sfadschm** [comment]
Should these keys replace the old ones in `HTTP.php` or duplicate? From #3961 in the main repo, the old ones in HTTP do not seem to be removed, is this intended?

**Comment by sba** [comment]
@sfadschm I translated `Security.php` - do you concur? (seen too late that these are also in `HTTP.php` - translated slightly different..

**Comment by paulbalandan** [comment]
> Should these keys replace the old ones in `HTTP.php` or duplicate? From #3961 in the main repo, the old ones in HTTP do not seem to be removed, is this intended?

Looking at the changes, those HTTP keys should have been removed as dupes.

**Comment by sba** [comment]
> Looking at the changes, those HTTP keys should have been removed as dupes.
But the keys are still present in:
`https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Language/en/HTTP.php`

**Comment by paulbalandan** [comment]
> > Looking at the changes, those HTTP keys should have been removed as dupes.
> 
> But the keys are still present in:
> `https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Language/en/HTTP.php`

Fixed in https://github.com/codeigniter4/CodeIgniter4/pull/3973

**Comment by paulbalandan** [comment]
@tangix  and @Terrorboy , would need some help updating `sv-SE` and `ko` for latest changes in `develop`. Thanks.

**Comment by Terrorboy** [comment]
@paulbalandan https://github.com/codeigniter4/translations/pull/205

**Comment by kenjis** [comment]
`Time.invalidFormat` is added.

I made a PR: #206

**Comment by tangix** [comment]
@paulbalandan 
PR: #207

**Comment by sfadschm** [comment]
@paulbalandan How to we handle the 4.0.5 to 4.1 differences?

**Comment by paulbalandan** [comment]
As the current workflow only looks at the main repo's `develop` branch, I guess we have to wait until 4.1 gets merged to develop before we can do anything.

**Comment by sfadschm** [comment]
I was rather wondering that after `4.1` was merged to `develop` and we update the translation repo to `4.1`, how can someone still download the translations for `4.0.5` afterwards if they want to stay with that version of the framework?
Will we do branches for translations, too?

**Comment by paulbalandan** [comment]
Ideally the flow should be that if there is a release in the main repo, the same should be done here. So if there is framework v4.0.5 there is also translations v4.0.5.

If ever this repo gets left behind, say 4.1 gets merged there before a release was made here, then all changes for 4.1 would be directed to a new branch.

**Comment by Terrorboy** [comment]
4.1.1 Do you proceed with translation?
Has any of the content already been translated?

**Comment by paulbalandan** [comment]
> 4.1.1 Do you proceed with translation?
> Has any of the content already been translated?

We cannot wait for the other locales if the maintainers are not active. We have to meet the long overdue release as promised. Besides, the translations will still work even if incomplete as we always fallback to English. If people want to have their locales updated to the latest, they need to step up and submit PRs, but that would be for the next releases.

**Comment by Terrorboy** [comment]
The work was proceeded because it was not confirmed whether the entire translation was in progress for v4.1.1.
After checking, when the v4.1.1 application is ready, please merge.

https://github.com/codeigniter4/translations/pull/215

**Comment by kenjis** [comment]
Add new lang item translation for ja #218

**Comment by Terrorboy** [comment]
@paulbalandan 
Can I write the Korean translation release number of readme.md as 4.1.1?
Or should I change it to 4.0.3?

**Comment by paulbalandan** [comment]
> @paulbalandan
> Can I write the Korean translation release number of readme.md as 4.1.1?
> Or should I change it to 4.0.3?

What do you mean?

**Comment by Terrorboy** [comment]
Should I change the release number to 4.1.1 or 4.0.3 in the next update?

![image](https://user-images.githubusercontent.com/5427199/111592108-b0f81c00-880b-11eb-844a-94926a4cc7b4.png)

**Comment by paulbalandan** [comment]
@Terrorboy the release number in the README.md corresponds to the version tag where the locale is first introduced to the repo. In this case, `ko` was introduced in `v4.0.2` that's why is tagged as `4.0.2` so this does not need to updated.

**Comment by paulbalandan** [comment]
Closing this as this does not receive the attention I expected for it. I have realized most of locales were made one-time-big-time and were pretty unmaintained since then. The help wanted label, therefore, is practically useless. If anyone wants to step up and update their locale of concern, you can do with a PR. Leaving this issue open is moot.

**Comment by tangix** [comment]
@paulbalandan
 is there an easy way for us to get the list of newly added or changed strings to translate for each release?

**Comment by paulbalandan** [comment]
The fastest way I can think of is running PHPUnit for the locale specifically: `vendor/bin/phpunit --filter SampleTranslationTest`

**Comment by pawelkg** [comment]
Hi! I've just send PR #250 with polish translations up to date.
