### ISSUE TITLE
Translations are not loaded from this repository

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/translations#169]
#144 changes the namespace.

```diff
    "autoload": {
        "psr-4": {
-           "Translations\\": ""
+           "CodeIgniter\\Language\\": "Language/"
        }
    },
```

It causes translations are not loaded from this repository, like <https://github.com/codeigniter4/CodeIgniter4/issues/2120>.

This is because the new namespace is:
```
prefix: CodeIgniter\Language
  path: vendor/composer/../codeigniter4/translations/Language/
```

When CI looks for `Language/it/Validation.php`, `Language::requireFile()` and `Services::locator()->search()` looks for `codeigniter4/translations/Language/Language/it/Validation.php`. And it can't find the lang file.

**Comment by paulbalandan** [comment]
@kenjis I forgot that CI4 autoloader ignores the `CodeIgniter` namespace from Composer. Can you check if fix solves the issue?

**Comment by kenjis** [comment]
Still does not work.

```
prefix: Translations
  path: vendor/composer/../codeigniter4/translations/Language/
```

So it looks for `codeigniter4/translations/Language/Language/it/Validation.php`.

**Comment by paulbalandan** [comment]
How about now?

**Comment by kenjis** [comment]
@paulbalandan Worked fine!
