### ISSUE TITLE
"Test Classes" do not conform to the psr-4 automatic loading standard

### ISSUE THREAD

**Issue by robsonpiere** [codeigniter4/translations#226]
When executing the installation via composer using the parameters -a or -o I get the following message:

Environment:

- OS: Windows 10
- PHP: 7.4.19
- Composer: 2.0.13
- codeigniter4/framework             v4.1.2  
- codeigniter4/translations            v4.1.1  

**Steps for reproduction:**

1 - Add translation
```bash
composer require codeigniter4/translations 
```

2 - add this option option in composer.json or perform the installation with the parameters 

```json
"config": {
        "optimize-autoloader":true
}
```
\+ 

```bash
composer i 
```

or

```bash
composer i -a
```

**Output:** 

> Generating optimized autoload files
> Class Translations\Tests\AbstractTranslationTestCase located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\AbstractTranslationTestCase.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\ArabicTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\ArabicTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\BrazilianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\BrazilianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\CzechTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\CzechTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\DutchTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\DutchTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\FarsiTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\FarsiTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\FrenchTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\FrenchTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\GermanTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\GermanTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\IndonesianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\IndonesianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\ItalianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\ItalianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\JapaneseTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\JapaneseTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\KoreanTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\KoreanTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\LatvianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\LatvianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\LithuanianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\LithuanianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\MalayalamTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\MalayalamTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\NorwegianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\NorwegianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\PolishTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\PolishTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\PortugueseTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\PortugueseTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\RussianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\RussianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\SimpleChineseTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\SimpleChineseTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\SinhalaTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\SinhalaTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\SlovakTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\SlovakTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\SpanishTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\SpanishTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\SwedishTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\SwedishTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\TraditionalChineseTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\TraditionalChineseTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\TurkishTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\TurkishTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\UkrainianTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\UkrainianTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.
> Class Translations\Tests\VietnameseTranslationTest located in C:/appfolder/vendor/codeigniter4/translations\Tests\Language\VietnameseTranslationTest.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by paulbalandan** [comment]
While the involved classes will not break your code as these are for testing purposes only, this is definitely a bug to the `.gitignore` specifically. Will fix. Thanks for bringing this up.
