### ISSUE TITLE
List of languages that contain untranslated items

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/translations#253]
The following language files contain untranslated items.

Translations are welcome!
Please read on the latest [Contributing guide][1] and how to run the specific locale tests in the [Test README][2],
when you are going to contribute.

[1]: https://github.com/codeigniter4/translations/blob/develop/CONTRIBUTING.md
[2]: https://github.com/codeigniter4/translations/blob/develop/tests/README.md

**Checklist of Completed Locales**
- [ ] ar
- [ ] cs
- [ ] de
- [ ] es
- [ ] fa
- [ ] id
- [ ] it
- [ ] lt
- [ ] lv
- [ ] ml
- [ ] nl
- [ ] no
- [ ] pt
- [ ] pt-BR
- [ ] ru
- [ ] si
- [ ] sk
- [ ] sv-SE
- [ ] th
- [ ] tr
- [ ] uk
- [ ] vi
- [ ] zh-CN
- [ ] zh-TW

#148

**Comment by kenjis** [comment]
update ID lang #254

**Comment by kenjis** [comment]
Update.

```
$ bin/test

...

The following locales have untranslated items:
ar
bs
cs
de
es
fa
fr
hu
id
it
ja
ko
lt
lv
ml
nl
no
pl
pt
pt-BR
ru
si
sk
th
tr
uk
vi
zh-CN
zh-TW
```

**Comment by kenjis** [comment]
Update:
```
The following locales have untranslated items:
ar
bs
cs
es
fa
fr
hu
it
ko
lt
lv
ml
nl
no
pl
pt
pt-BR
ru
si
sk
sv-SE
th
tr
uk
vi
zh-CN
zh-TW
```

**Comment by kenjis** [comment]
CodeIgniter v4.2.0 will come soon.

```
The following locales have untranslated items:
ar
bs
cs
es
fa
fr
hu
it
ko
lt
lv
ml
nl
no
pl
pt
ru
si
sk
th
tr
uk
vi
zh-CN
zh-TW
```

**Comment by ed3** [comment]
- updated `hu`
- add `ro` language

**Comment by kenjis** [comment]
We've got the translation status page:
https://codeigniter4.github.io/translations/
