### ISSUE TITLE
Back after a long break in translation.

### ISSUE THREAD

**Issue by 0x0undefined** [codeigniter4/translations#311]
Hello, I'm [DEVELPL](https://github.com/DEVELPL) (first Polish language contributor) on new account.
If you want I can continue to do translations for you. 

Greetings.

**Comment by kenjis** [comment]
Thank you!
`pl` has untranslated items now.
See https://github.com/codeigniter4/translations/issues/253#issuecomment-1145785919

**Comment by paulbalandan** [comment]
@0x0undefined thank you for the initiative. `pl` has many untranslated items since your last translation. You can send a PR for those anytime.

Closing this for the mean time.
