### ISSUE TITLE
[feature-request] Translation Status Feature Suggestions

### ISSUE THREAD

**Issue by Terrorboy** [codeigniter4/translations#349]
Thanks for providing such a good tool.
I'd like to suggest one.

What is missing is checked, but what has been changed seems difficult to check.
Could you also provide the changed content?

It seems that you can check the changes with a comment base like https://github.com/codeigniter-kr/ci4lang

![CleanShot 2022-12-02 at 13 47 05](https://user-images.githubusercontent.com/5427199/205216890-af5be0d0-b75d-466e-9c54-60c279ad06e1.png)

**Comment by kenjis** [comment]
We have a script to add en lang strings as comments
See #330

**Comment by Terrorboy** [comment]
Great!
Are you waiting for a comparison between inline comment and en language value?

If so, feel free to close this issue

**Comment by kenjis** [comment]
The script can be used by translators, but it has minimal functionality.

If a translator includes the latest English strings as comments after the translation is complete, the comments can be updated by running the script again after the English strings have changed. 

So it makes easier to find the changes with `git diff`.

**Comment by Terrorboy** [comment]
Okay.

If more features are needed, I will modify it and use it.

I will close this issue.
