### ISSUE TITLE
In some cases, the original sentence is used in translation ...

### ISSUE THREAD

**Issue by Terrorboy** [codeigniter4/translations#357]
In some cases, the original sentence is used in translation, and in this case, it is picked up as an error in the test.

![CleanShot 2023-01-12 at 09 38 37](https://user-images.githubusercontent.com/5427199/211948444-189e7cf9-a091-4f2c-91fc-da5ea6e6bf23.png)
![CleanShot 2023-01-12 at 09 40 47](https://user-images.githubusercontent.com/5427199/211948693-f2a079e9-bc28-4165-907f-fe39ce274cba.png)

https://github.com/codeigniter4/translations/actions/runs/3898069200/jobs/6656412790#step:9:30

**Comment by kenjis** [comment]
Update your lang Test file.
See https://github.com/codeigniter4/translations/blob/develop/tests/Language/JapaneseTranslationTest.php

**Comment by Terrorboy** [comment]
@kenjis thank you

**Comment by Terrorboy** [comment]
https://github.com/codeigniter4/translations/commit/48763b784738ac1614c02a09bd7d79e0ee42fd74
